### ISSUE TITLE
Exclude Specific Torrents

### ISSUE THREAD

**Issue by shawncruiksh** [omaralvarez/deluge-autoremoveplus#12]
I'd like to request that an enhancement be made, whereby we can exclude specific torrents from being removed (via a right click menu option).

**Comment by omaralvarez** [comment]
Hi, this functionality already exists:

![exempt-torrent 1](https://cloud.githubusercontent.com/assets/5764407/11014587/66f90f5a-853d-11e5-8191-f9816797662f.png)
