### ISSUE TITLE
How do I get the .egg file? Deluge forums hacked and down for some time now

### ISSUE THREAD

**Issue by ghost** [omaralvarez/deluge-autoremoveplus#14]
How do I get the .egg file? Deluge forums hacked and down for some time now

**Comment by ghost** [comment]
Figured it out 

git cloned then

```
python setup.py bdist_egg
```

then look in the dist directory

**Comment by omaralvarez** [comment]
You can also look in:

https://github.com/omaralvarez/deluge-autoremoveplus/releases

There you have all the releases and the corresponding eggs for python 2.6 and 2.7.

Cheers.

**Comment by ghost** [comment]
Ohhhh , ty
