### ISSUE TITLE
Feature Request: Only remove torrents with a specific label

### ISSUE THREAD

**Issue by Jektt** [omaralvarez/deluge-autoremoveplus#15]
Hi, 

So I see in the new version you can add torrents with specific labels to NOT be removed. But I think the opposite would be more useful.

When Sickrage snatches torrents they can be added to deluge with a label, I would only like these torrents to be effected.

I tried adding an empty Label to the exclusion list as a work around so it wouldn't effect torrents added manually without labels but this didn't work. 

Any way to do what I want with the current implementation? Or can this feature be put in?

**Comment by Jektt** [comment]
Decided to do this myself. Only requires some very slight changes. nvm.

**Comment by omaralvarez** [comment]
If you finally implement this, please make a pull request. If not, I think this will be a neat feature and might implement it myself. Although I believe there should be a way to change the desired behaviour in the UI.

**Comment by dgw** [comment]
I would like this, too. @Jektt, would you mind sharing the implementation, if you wrote it?
