### ISSUE TITLE
exempted label filter does not work correctly

### ISSUE THREAD

**Issue by tobiasdf** [omaralvarez/deluge-autoremoveplus#16]
Hi, 
the exempted label filter does just work if every torrent does have an label or none.

Deluge has an AutoAdd (WatchFolder) feature, if this feature is used and the label plugin is active, then deluge adds them with "no label". If you try now to add just an label filter in the autoremoveplus plugin, it will not work until i give the torrent a label witch is not listed in the exempted label list.
thank you for the plugin!

**Comment by omaralvarez** [comment]
Would you care to elaborate some more on this issue, because I do not understand what is the problem. Is anybody else experiencing this?

**Comment by tobiasdf** [comment]
If you have torrents with label an some with no label in the dl-queue, and you have set a label filter , the plugin will not work anymore.It seems like it has problems with "no labeld torrents".

TestCase: 1. add torrent with label, 2. add torrent with no label, 3. set an labelfilter rule, 4. wait until rule shoud do something; Result: nothing will happen.

**Comment by omaralvarez** [comment]
Got it, thanks a lot, I will try to reproduce and fix this ASAP.

**Comment by omaralvarez** [comment]
Just wanted to check if people want a release with this fix right now or do not mind waiting for the 0.6.

**Comment by bootldrDNB** [comment]
a new release would be nice :)

**Comment by omaralvarez** [comment]
@bootldrDNB Done!

**Comment by bootldrDNB** [comment]
sick! gonna test asap.
