### ISSUE TITLE
 Feature Request: Multiple settings based on label

### ISSUE THREAD

**Issue by mmarquezs** [omaralvarez/deluge-autoremoveplus#17]
It would be very useful to be able to make different settings based on for example the label.

This way I can set it to autoremove some torrents daily and others after a week, etc..

**Comment by ghost** [comment]
It was my first idea leading to that: https://github.com/omaralvarez/deluge-autoremoveplus/issues/7

**Comment by omaralvarez** [comment]
Yes, this is the logical next step. I think in march I will have time to work on the plugin. I will fix some bugs, and probably add something like this.

**Comment by Jektt** [comment]
This feature would be fantastic! Hope you find the time to implement it soon. I can't help with coding this, but will make a basic mockup of what I think the layout should be.

http://i.imgur.com/VxcARu8.png

**Comment by omaralvarez** [comment]
Ok, I will be starting work on this feature for the new version. Finally it looks like I will have some time!

**Comment by swemoney** [comment]
Throwing my hat in the "excited for this feature" pool! I think @Jektt has a fantastic mockup. My personal favorite is the Tracker or Label dropdown so you can specify individual tracker settings while a label might contain many trackers. Can't wait!

**Comment by ldexterldesign** [comment]
+1

Hey,

Thanks for software

In the meantime, what other solutions are people using to keep track of which torrents are from which indexers?

Hope to hear back

Kind regards

**Comment by ldexterldesign** [comment]
BUMP

**Comment by omaralvarez** [comment]
For now, I don't think there is a way to do it. The only thing you can do now is delete selectively torrents with labels or tracker name. I am working on this feature, but it is a complex one an it will take some time.

**Comment by ldexterldesign** [comment]
Hey @omaralvarez,

Thanks for reply

Yea, for the time being, I've configured my Deluge settings to seed everything to at least 1:1 ratio before removing, to cover the private tracker requirements, and will selectively prune public trackers if I'm running low on disk space

Needless to say, certainly a solution needed for this use case

Good luck with the work - be sure to leave this issue open and follow up if/when you devise a solution

Yours faithfully
