### ISSUE TITLE
Moving data files on removal

### ISSUE THREAD

**Issue by ghost** [omaralvarez/deluge-autoremoveplus#18]
Would it be possible to add a move the data files on removal option to this plugin?

**Comment by omaralvarez** [comment]
What you ask is  certainly possible, but there is already a plugin for that, if I'm not mistaken.

**Comment by ghost** [comment]
After more reading I was able to accomplish this by coding a script and using the Execute plugin. Thanks Though

**Comment by omaralvarez** [comment]
No problem, ideas are always welcome.
