### ISSUE TITLE
Option to PAUSE instead of remove torrents

### ISSUE THREAD

**Issue by neatchee** [omaralvarez/deluge-autoremoveplus#2]
Per forum post:

> I would love to see one additional option added (or perhaps you can give some guidance on how to modify the plugin to do this?):
> 
> Option to PAUSE instead of remove matched torrents.
> 
> I would use the default Deluge Queue for this, but I need certain trackers to be exempt, which is why I LOVE this plugin! But it would be great if I could have them pause instead of being removed, so that I don't lose track of new torrents that get auto-added from my RSS feeds. Right now, sometimes a torrent will get added, finish downloading, and hit the ratio limit set in AutoRemovePlus before I even notice it's been added at all! :)

**Comment by omaralvarez** [comment]
I'll try to get this ready in the 0.5 release.

**Comment by cron410** [comment]
keep being awesome Omar!

**Comment by neatchee** [comment]
Thanks, Omar! That would be awesome!

**Comment by neatchee** [comment]
Omar, you are a ROCKSTAR! This makes me so happy! Keep up the AMAZING work :)

**Comment by neatchee** [comment]
Just wanted to come back and let you know that I built the egg from source with this patch included and can confirm that everything is working as expected. Thanks again, Omar!

**Comment by omaralvarez** [comment]
Thanks a lot for the testing and support. One more feature to go and I'll release the 0.5 version!
