### ISSUE TITLE
Opposite of exemption

### ISSUE THREAD

**Issue by Ghosthree3** [omaralvarez/deluge-autoremoveplus#23]
Would it be possible to get a second list box which works inverse to the exemption rules box where only trackers listed in that box are affected, the opposite box would have to be empty for either to work. I don't know about other people but for me this way actually seems more useful, instead of excluding all the trackers I use that aren't the one I want to auto remove on I can just add the one I want to remove on.

**Comment by omaralvarez** [comment]
Ok, so with the new changes I'm introducing, I believe that this will be possible. To remove only torrents pertaining to a tracker or label, one just needs to include them in the new specific rule list, and it will ignore the normal remove rules for these torrents. So, this will be available in 0.6.

**Comment by omaralvarez** [comment]
Ok, this is done. 

With the new version disable the general rules and just use tracker specific rules.
