### ISSUE TITLE
Delete first the oldest torrents and stop when there is enough free space

### ISSUE THREAD

**Issue by JohanPy** [omaralvarez/deluge-autoremoveplus#26]
I would like to delete first the oldest torrents and stop deleting torrents when there is enough free space.

Details:
I use a big dedicated hard drive in order to keep in seed my torrents as long as possible. But I need to be sure there is enough free space for downloading new torrents.
When autoremoveplus detects there is no enough free space on my hard drive it removes all torrents which match my criteria (ratio > 1).  So it removes the majority of my torrents and after it don't remove anything during weeks/months.
I would like to frequently remove the oldest torrents which match with autoremoveplus's criteria in order to keep a minimal free space.

If you understand what I want and think that could be useful, I can try to add this functionality _(I never worked on a deluge plugin so this may be long and unsuccessful )_

**Comment by dgw** [comment]
You might find the discussion in #22 at least a little enlightening, though I still don't really understand how it works. I just know that my config works for me, filtered based on minimum seed time and the number of torrents I can usually fit on my server.

**Comment by JohanPy** [comment]
Thank you.
I will close my issue, that answer my question. I think there is no more problem in the last version.

**Comment by Enf0** [comment]
Sorry to bump an old issue, but how did you solve this?

I'm in a similar situation as you: I want to make sure there is always enough disk space for new torrents.

I would like AutoRemovePlus to simply start deleting the oldest added torrents whenever my free disk space goes below a certain threshold, and stop deleting whenever the free disk space is again above the threshold.

When trying this however, it seems that as soon as the disk space goes below "Minimum HDD Space", it just removes everything in the list.

**Comment by omaralvarez** [comment]
That is not the way it works. If I remember correctly, it does not check the disk space after every torrent removed. It will remove every torrent until the total number of torrents is equal to the desired number of torrents. So, in short it only checks disk space before removal, so that is why you are seeing that behaviour. I haven't been able to work on this project for a while, so I hope my explanation is correct and I didn't forget anything.
