### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by ghost** [omaralvarez/deluge-autoremoveplus#27]
Hi,

I have an error with version 0.6.1
js/autoremoveplus/autoremoveplus.js 
404

Using raspbian and a raspberry pi.

:s

**Comment by omaralvarez** [comment]
Could you check on the Javascript console what it says? I need a little more info about the error... When did the error occur? When loading the plugin?

**Comment by ghost** [comment]
Deluge client on Windows doesnt open anymore.
On the web ui, nothing more than js/autoremoveplus/autoremoveplus.js 404 (Not Found)
12

**Comment by omaralvarez** [comment]
So from the errors that you are describing, it seems the installation is broken. Have you tried, deleting the plugin and adding it again? Erasing the config file to reset settings? Are you sure that you have used the correct egg for your Python version? Have you made sure that the plugin was updated on the server? Please tell me what is your Deluge version and I will try to test the plugin with your OS if I can.

**Comment by ghost** [comment]
Hey,

Thanks for your quick answer.
Correct version of Python: Yes.
I've also installed it correctly on my remote client (Wndows with 2.6) and server (Linux with 2.7).

I will try to find the plugin folders for both and properties one too to be sure it's cleaned.

Linux: ~/.config/deluge/plugins
Windows: %APPDATA%\deluge\plugins

But where is the properties file?

**Comment by omaralvarez** [comment]
In the deluge directory there is an autoremoveplus.conf, make a copy and
delete it. Also please remember to tell me your Deluge version.

**Comment by ghost** [comment]
A clean did the job. Thanks.
