### ISSUE TITLE
Tracker Settings

### ISSUE THREAD

**Issue by eseelke** [omaralvarez/deluge-autoremoveplus#3]
I would like to submit a feature request.

Would like to be able to have different settings based on which tracker is used.

For instance, I would like to have a default ratio and seed time for all trackers. But, if using tracker 'something.com', I would like to have different ratio and seed times. So, instead of exempting, adding different settings.

Thanks, Eddie

**Comment by omaralvarez** [comment]
This is a complex request, right now I don't have much time to develop new features, I will leave this in my TODO list. I will probably have time in October to add new functionality, but I may implement more simple features first.

**Comment by ldexterldesign** [comment]
Hey,

Thanks for software

Apologies for my naivety, but how is this issue different from https://github.com/omaralvarez/deluge-autoremoveplus/issues/17 ?

Hope to hear back

Kind thanks

**Comment by omaralvarez** [comment]
It is essentially the same thing, but for trackers instead of labels. I guess this could be merged with #17 but I feel is not exactly the same thing.

**Comment by ldexterldesign** [comment]
Cheers for reply

Yea, I see what you mean - just thought I'd get clarification

I see your milestone goal is 2016-08-31 ( https://github.com/omaralvarez/deluge-autoremoveplus/milestone/2 ), so I'll follow this up then

Good luck with the release!

Kind thanks

**Comment by omaralvarez** [comment]
Yes, but to be honest I am up to my neck in work, so bare in mind this is an optimistic estimate. I may not be able to meet the deadline.
