### ISSUE TITLE
Do not remove if below X seeders

### ISSUE THREAD

**Issue by thomasfinstad** [omaralvarez/deluge-autoremoveplus#32]
In the features section it says you can remove by seeders 

> Choose to remove or pause them based on multiple criteria age, **seeders**, seed time or ratio.

Maybe I am misunderstanding, since I cannot find this setting anywhere, but in any case I would love to have an option for **Do not remove torrents with less than X seeders** already uploading the torrent.

This would be great when it comes to helping the community keeping torrents healthy without having to manually check everything.

**Comment by omaralvarez** [comment]
The option that you are asking for is already present, you can select in the ```remove by:``` dropdown menu seeders, and then set a minimum in the field next to it, and that will not remove any torrent that has less seeders than the minimum amount of seeders that you want.

**Comment by thomasfinstad** [comment]
I run deluge in a server (daemon) - client setup.
After I manually removed the older version of the plugin on the server side, and restarted the daemon I now get the option of **seeders** in the dropdown. Thank you for all your work.

**Comment by omaralvarez** [comment]
No problem, I am glad you were able to sort it out.
