### ISSUE TITLE
WEB UI

### ISSUE THREAD

**Issue by Quiksmage** [omaralvarez/deluge-autoremoveplus#43]
Hi,
You mention on the details of this page that it works with the webui.

When I try to enable it on the webui, it never stays checked.

When I check the logs, I see the following

[INFO    ] 12:00:25 pluginmanager:108 'AutoRemovePlus' plugin contains no WebUI code, ignoring WebUI enable call.

Is the webui a deprecated part of this plugin or did I do something wrong possibly?

**Comment by dgw** [comment]
I haven't used this plugin for a while, but under Deluge 1.3.x I did use it with the webui. It should work… unless the Deluge team changed something in 1.3.14/5? There were CSRF and directory traversal bugfixes in those releases that I suppose could have broken the webui functionality of this plugin.

**Comment by Quiksmage** [comment]
I figured it out. The egg file has to be installed on both the gtkui and
web ui to work in both respective places.
