### ISSUE TITLE
Be able to move/archive torrents instead of deleting them

### ISSUE THREAD

**Issue by NinoFoxx** [omaralvarez/deluge-autoremoveplus#47]
It would be cool to have a feature that allows you to archive old torrents to another hard drive, or network drive, to free up space on the main storage.

I couldn't find any other plugin that does that.

Thank you!

**Comment by jancsicso** [comment]
You can use Execute plugin in combination with this plugin to move deleted torrents to a new place.

**Comment by NinoFoxx** [comment]
Sorry, I forgot to close this.
