### ISSUE TITLE
Deluge 2.0 Docker Support

### ISSUE THREAD

**Issue by clifford64** [omaralvarez/deluge-autoremoveplus#52]
I have placed the new python 3.7 .egg plugin within the /deluge/plugin directory for the container, but the plugin does not show up within deluge. I have restarted the container multiple times as well as restarted the host machine.

**Comment by wogam** [comment]
Try my solution here:
https://github.com/omaralvarez/deluge-autoremoveplus/pull/51#issuecomment-516388171
