### ISSUE TITLE
installed plugin but wont activate

### ISSUE THREAD

**Issue by y0da822** [omaralvarez/deluge-autoremoveplus#57]
Running in docker conatiner from linuxserver.io
Container has python 3.6
Created egg file using 3.6
COpiedd egg file to plugins folder
I see it in the plugins in webui - I check the box to turn it on and it unchecks itself by next time i go into plugins.

**Comment by y0da822** [comment]
Switched over to https://github.com/springjools/deluge-autoremoveplus

**Comment by Merlincool** [comment]
> Switched over to https://github.com/springjools/deluge-autoremoveplus

Did it worked?

**Comment by y0da822** [comment]
> > Switched over to https://github.com/springjools/deluge-autoremoveplus
> 
> 
> 
> Did it worked? 

Yes it worked.

**Comment by Merlincool** [comment]
> > > Switched over to https://github.com/springjools/deluge-autoremoveplus
> > 
> > 
> > Did it worked?
> 
> Yes it worked.

Sorry it doesn't seems to work for deluge 2.0.3, if I was not clear earlier. Have you found any work around with Deluge 2.0.3 on debian 10 based seedbox

**Comment by y0da822** [comment]
> > > > Switched over to https://github.com/springjools/deluge-autoremoveplus
> > > 
> > > 
> > > Did it worked?
> > 
> > 
> > Yes it worked.
> 
> Sorry it doesn't seems to work for deluge 2.0.3, if I was not clear earlier. Have you found any work around with Deluge 2.0.3 on debian 10 based seedbox

I just checked my stuff over - I am running Ubuntu 16 on the seedbox.  Deluge container from linuxserver.io.

![deep](https://user-images.githubusercontent.com/54944216/114554022-45e80c80-9c34-11eb-8511-1eca4601e7c3.PNG)

AutoRemovePlus 2.0.0.

**Comment by Merlincool** [comment]
> > > > > Switched over to https://github.com/springjools/deluge-autoremoveplus
> > > > 
> > > > 
> > > > Did it worked?
> > > 
> > > 
> > > Yes it worked.
> > 
> > 
> > Sorry it doesn't seems to work for deluge 2.0.3, if I was not clear earlier. Have you found any work around with Deluge 2.0.3 on debian 10 based seedbox
> 
> I just checked my stuff over - I am running Ubuntu 16 on the seedbox. Deluge container from linuxserver.io.
> 
> ![deep](https://user-images.githubusercontent.com/54944216/114554022-45e80c80-9c34-11eb-8511-1eca4601e7c3.PNG)
> 
> AutoRemovePlus 2.0.0.

Are you able to execute function with that? I am with Pulsedmedia and 

python --version = 2.7.(something)
python3 --version = 3.8.(something)

renaming to Autoremoveplus-2.0.0-py3.8.egg doesn't show my plugin in deluge (Of course I have restarted deluge).

renaming to Autoremoveplus-2.0.0-py2.7.egg does show plugin in deluge, but now the function is not executed. Though plugin appears in deluge (yes I have hit checkbox and it appears in list of plugins on left side of settings, below Autoadd etc)

I have no clue why *3.8.egg doesn't show me plugin but *2.7.egg does show but now it's not executable.

**Comment by y0da822** [comment]
I was able to launch python 3.6 - and come to think of it, I had to compile that egg file using python 3.6.  Renaming the egg doesn't work, I had to actually compile some way but I dont remember what I did there.

![deep](https://user-images.githubusercontent.com/54944216/114558127-5ac69f00-9c38-11eb-90a3-5be074f0489b.PNG)
