### ISSUE TITLE
Remove by: HDD space

### ISSUE THREAD

**Issue by jkaberg** [omaralvarez/deluge-autoremoveplus#6]
I'd love to see an option to remove torrents (based on highest ratio? when low on HDD space

Example:

Remove by: HDD space Min: 50GB

That way I know my seedbox will seed as long as possible but will never run out of space for new torrents

**Comment by dgw** [comment]
Exactly what I clicked on this plugin for, browsing the Deluge wiki, hoping it could do precisely this.

**Comment by omaralvarez** [comment]
This is probably the easiest thing to implement in the current backlog. I'll try to get this also in the next release, although I'm not sure I'll be able to have it ready this month. As soon as I can, I'll work on all of the new features.

**Comment by jkaberg** [comment]
Thank you @omaralvarez

**Comment by jkaberg** [comment]
Ok so testing this a bit now but doesn't seem to work as expected, this is how I have it setup: https://db.tt/a7xHHbCb

Now my HDD usage is below 90GB and I have other torrents then the ones @ passthepopcorn in my torrent list @omaralvarez

**Comment by omaralvarez** [comment]
Your issue is the **Max Torrents** option. You have it set to -1, so no torrents will be removed, you should set it to the number of torrents you want to keep (20, 200, etc.). If you want to remove every torrent that meets the criteria, set it to 0.

**Comment by jkaberg** [comment]
Ah okay @omaralvarez , but if I only want to remove torrents up to >= 90GB? ( I don't want to remove all torrents, just enough ones to keep seeding while still being able to download new ones. So if below the threshold of 90GB remove enough torrents so what we are above 90GB again)

(you said every torrent so just need some clarification)

**Comment by jkaberg** [comment]
Sent you an PR https://github.com/omaralvarez/deluge-autoremoveplus/pull/13 @omaralvarez
