### ISSUE TITLE
Maximum torrents add a checkbox to enable it

### ISSUE THREAD

**Issue by ghost** [omaralvarez/deluge-autoremoveplus#9]
It should be 0 not -1

**Comment by omaralvarez** [comment]
No, it should not, -1 means that the plugin is disabled. If a user would install the plugin and it would have 0 it would start deleting every torrent that meets the requirements, that is every single torrent with default settings. So this cannot be changed to 0 initially.

**Comment by ghost** [comment]
I understand that.
We should add an hint somewhere because it's not really easy to understand that option... 
(Few users on the forum were stuck)

**Comment by omaralvarez** [comment]
Yes, you are right, maybe changing the label to (-1 to disable) or adding a check button would be better.

**Comment by ghost** [comment]
Exactly what I tought, a checkbox.
